# `~/.config/starship.toml` サンプル

```zsh
# ~/.config/starship.toml

"$schema" = '[https://starship.rs/config-schema.json](https://starship.rs/config-schema.json)'

add_newline = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[aws]
symbol = "☁️  "
format = '[$symbol($profile )(\($region\) )]($style)'
style = 'bold yellow'

[git_branch]
symbol = "🌱 "
format = '[$symbol$branch]($style) '
style = 'bold purple'

[node]
symbol = "⬢ "
format = '[$symbol($version )]($style)'
style = 'bold green'
```
